from django.core.exceptions import ValidationError


def validate_audio_file(audio_file):
    pass